### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ib00** [MrFrenik/gs_examples#16]
I get some compile errors in gs_gui (trying to compile example 25, gs_gui):

../../third_party/include/gs/util/gs_gui.h:7679:21: error: conflicting types for ‘gs_gui_gizmo’; have ‘int32_t(gs_gui_context_t *, gs_camera_t *, gs_vqs *, float,  int32_t,  int32_t,  int32_t)’ {aka ‘int(struct gs_gui_context_t *, gs_camera_t *, gs_vqs *, float,  int,  int,  int)’}
 7679 | GS_API_DECL int32_t gs_gui_gizmo(gs_gui_context_t* ctx, gs_camera_t* camera, gs_vqs* model, float snap, int32_t op, int32_t mode, int32_t opt)
      |                     ^~~~~~~~~~~~
In file included from ../source/main.c:18:
../../third_party/include/gs/util/gs_gui.h:1076:21: note: previous declaration of ‘gs_gui_gizmo’ with type ‘int32_t(gs_gui_context_t *, gs_camera_t *, gs_vqs *, int32_t,  int32_t,  int32_t)’ {aka ‘int(struct gs_gui_context_t *, gs_camera_t *, gs_vqs *, int,  int,  int)’}
 1076 | GS_API_DECL int32_t gs_gui_gizmo(gs_gui_context_t* ctx, gs_camera_t* camera, gs_vqs* xform, int32_t op, int32_t mode, int32_t opt);

**Comment by MrFrenik** [comment]
This should be fixed now

**Comment by ib00** [comment]
Thanks for fixing this.

Is there an example of gs_gui_gizmo usage?

**Comment by MrFrenik** [comment]
Not yet, but I'll add it in the `gs_gui` example for everyone.

**Comment by MrFrenik** [comment]
> Thanks for fixing this.
> 
> Is there an example of gs_gui_gizmo usage?

Added a gizmo example here: https://github.com/MrFrenik/gs_examples/tree/main/ex_util_gui/gizmo

**Comment by ib00** [comment]
Thank you! Fantastic project!

The only thing I am noticing is that compile times are a bit slow. But that's the nature of
single-header design.

**Comment by MrFrenik** [comment]
For your compile times, what platform are you using and how are you building? If they become too large, you can of course compile the framework into a static lib then use it that way as well.
