### ISSUE TITLE
One build file.

### ISSUE THREAD

**Issue by SushilRagoonath** [MrFrenik/gs_examples#4]
Considering the large amount of new examples being added I think it would nice to have a repo wide build file that build all the examples This way any projects that use outdated apis are easy to notice and fix.

**Comment by MrFrenik** [comment]
Agreed, this has been on my to-do list for a while, along with cmake/premake build files for the entire repo as well.

**Comment by thecardinelli** [comment]
Ahhh this is basically i think what i was wondering about in https://github.com/MrFrenik/gunslinger/issues/22

**Comment by SushilRagoonath** [comment]
Cool, check the pull requests,I made a shell script but havent added emscriptem yet
